server:
  port: ${ADAPTER_PORT:9001}

spring:
  flyway:
    schemas: public
    enabled: true
  datasource:
    url: ${DATA_SOURCE:jdbc:postgresql://localhost:5435/costs}
    username: ${DATA_SOURCE_USERNAME:marvin}
    password: ${DATA_SOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

camt:
  import:
    file:
      in: ${CAMT_DIRECTORY_IN:./app/camt}
      done: ${CAMT_DIRECTORY_DONE:./app/camt/done}
    costs:
      special:
        limit: 50

importer:
  in:
    costs: ${IMPORTER_IN_COSTS:./app/import/costs}
    sensordata: ${IMPORTER_IN_SENSORDATA:./app/import/sensordata}
    vocabulary: ${IMPORTER_IN_VOCABULARY:./app/import/vocabulary}
  done: ${IMPORTER_DONE:./app/import/done}

exporter:
  folder: ${EXPORTER_FOLDER:./app/export}

uploader:
  enabled: false
  credentials:
    path: ${UPLOADER_CREDENTIALS_PATH:./app/google/credentials.json}
  cost-export-folder: ${UPLOADER_COST_EXPORT_FOLDER:./app/export}
  parent-folder-name: backup

influxdb:
  #  url: ${INFLUX_URL:http://localhost:8086}
  #  token: ${INFLUX_TOKEN:temp-init-token-will-be-replaced}
  url: ${INFLUX_URL:http://influxdb.home-lab.com}
  token: ${INFLUX_TOKEN:rmz5aaaKYSpgvXSO3C1UFZmXjvtpwI81b7hcMaMJJqOTjvgI82iNAbSsF7fpGIy2fduNDKACQ759cyaiECrulg==}
  org: ${INFLUX_ORG:wildfly_domain}
  export:
    enabled: ${INFLUXDB_EXPORT_ENABLED:false}

consul:
  url: ${CONSUL_URL:http://192.168.178.29:8500}

logging:
  level:
    org.springframework: INFO

management:
  health:
    mail:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "prometheus,info,beans"
